version: '3'
services:
  biosample-ld:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/inutano/biosample_jsonld
    container_name: biosample-ld
    user: ${UID}
    volumes:
      - .:/work
    command:
      - "bs2ld"
      - "jsonld"
      - "SAMD00000345"
